Work on in action.

diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -1,3 +1,73 @@
 #!/bin/bash
 
-echo "{}"
+set -e
+
+exec 3>&1 # make stdout available as fd 3 for the result
+exec 1>&2 # redirect all output to stderr for logging
+
+export root=`dirname $0 | while read a; do cd $a && pwd && break; done`
+
+source "${root}/common.sh"
+
+dest="${1}"
+
+if [ -z "${dest}" ]; then
+  echo "usage: $0 <path/to/destination>"
+  exit 1
+fi
+
+payload=$(mktemp ${TMPDIR:-/tmp}/sonarqube-resource-out.XXXXXX)
+cat > $payload <&0
+
+sonar_host_url=$(jq -r '.source.host_url // ""' < "${payload}")
+if [ -z "${sonar_host_url}" ]; then
+  echo "host_url param has not been specified."
+  exit 1
+fi
+
+sonar_login=$(jq -r '.source.login // ""' < "${payload}")
+if [ -z "${sonar_login}" ]; then
+  echo "sonar_login param has not been specified."
+  exit 1
+fi
+
+sonar_password=$(jq -r '.source.password // ""' < "${payload}")
+
+ce_task_id=$(jq -r '.version.ce_task_id // ""' < "${payload}")
+if [ -z "${ce_task_id}" ]; then
+  echo "version to fetch cannot be determined: ce_task_id not set?"
+  exit 1
+fi
+
+cd "${dest}"
+
+ce_task_info="./ce_task.json"
+ce_task_status="PENDING"
+until [ "${ce_task_status}" != "PENDING" ] && [ "${ce_task_status}" != "IN_PROGRESS" ]; do
+  sq_ce_task "${sonar_login}:${sonar_password}" "${sonar_host_url}" "${ce_task_id}" > "${ce_task_info}"
+  ce_task_status=$(jq -r '.task.status // ""' < "${ce_task_info}")
+  if [ "${ce_task_status}" != "PENDING" ] && [ "${ce_task_status}" != "IN_PROGRESS" ]; then
+    sleep 5 # Poll SonarQube compute engine task every 5 seconds.
+  fi
+done
+
+analysis_id=""
+if [ "${ce_task_status}" == "SUCCESS" ]; then
+  analysis_id=$(jq -r '.task.analysisId // ""' < "${ce_task_info}")
+  if [ -z "${analysis_id}" ]; then
+    echo "no analysis ID could be fetched from compute engine task result"
+    exit 1
+  fi
+fi
+
+project_status="./qualitygate_project_status.json"
+sq_qualitygates_project_status "${sonar_login}:${sonar_password}" "${sonar_host_url}" "${analysis_id}" > "${project_status}"
+
+# TODO Parse contents of project_status and popuplate metadata.
+
+jq -n "{
+  version: { ce_task_id: \"${ce_task_id}\"},
+  metadata: [
+      { name: \"ce_task_status\", value: \"${ce_task_status}\" }
+  ]
+}" >&3
