Polish stuff and add some new features
- Fixes #13 - anonymous analysis without username/password or auth token
- Add __debug flag to ease development of the resource itself
- Use maven wrapper if present to perform analysis
- Enhance unit test framework code

diff --git a/test/mocks/sonar-scanner b/test/mocks/sonar-scanner
--- a/test/mocks/sonar-scanner
+++ b/test/mocks/sonar-scanner
@@ -1,2 +1,9 @@
 #!/usr/bin/env bash
+if [[ ! -f "${SONAR_SCANNER_REPORT_FILE_MOCK}" ]]; then
+  echo "!! ERROR DURING INVOCATION OF sonar-scanner MOCK FUNCTION !!"
+  echo "The variable SONAR_SCANNER_REPORT_FILE_MOCK points to a non-existent file location or" >&2
+  echo "the file at the specified location cannot be read:" >&2
+  echo "--> \"${SONAR_SCANNER_REPORT_FILE_MOCK}\"" >&2
+  exit 1
+fi
 cat "${SONAR_SCANNER_REPORT_FILE_MOCK}" > "${SONAR_SCANNER_REPORT_FILE}"
